# Generated by Django 3.2.19 on 2023-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
